import { NextResponse } from "next/server"
import { getSimulationLogs, createSimulationLog, verifyLogIntegrity } from "@/lib/db"
import type { SimulationLogData } from "@/lib/db"

export async function GET() {
  try {
    const logs = await getSimulationLogs()
    return NextResponse.json({ success: true, logs })
  } catch (error) {
    console.error("Error fetching logs:", error)
    return NextResponse.json(
      { success: false, message: "Failed to fetch simulation logs", error: String(error) },
      { status: 500 },
    )
  }
}

export async function POST(req: Request) {
  try {
    const body = await req.json()
    const logData: SimulationLogData = body.logData

    // Validate required fields
    if (
      !logData.startTime ||
      logData.duration === undefined ||
      logData.vehicleCount === undefined ||
      logData.inflowRate === undefined ||
      logData.averageSpeed === undefined ||
      logData.autoGeneratedRatio === undefined
    ) {
      return NextResponse.json({ success: false, message: "Missing required fields" }, { status: 400 })
    }

    const logId = await createSimulationLog(logData)
    return NextResponse.json({ success: true, logId })
  } catch (error) {
    console.error("Error creating log:", error)
    return NextResponse.json(
      { success: false, message: "Failed to create simulation log", error: String(error) },
      { status: 500 },
    )
  }
}

export async function PUT(req: Request) {
  try {
    const body = await req.json()
    const { id } = body

    if (!id) {
      return NextResponse.json({ success: false, message: "Log ID is required" }, { status: 400 })
    }

    const isValid = await verifyLogIntegrity(id)
    return NextResponse.json({ success: true, isValid })
  } catch (error) {
    console.error("Error verifying log:", error)
    return NextResponse.json(
      { success: false, message: "Failed to verify log integrity", error: String(error) },
      { status: 500 },
    )
  }
}
