"use client"

import { useState, useEffect } from "react"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Search, ArrowUpDown, Calendar, Clock, Car, Gauge, RotateCw, Download } from "lucide-react"
import { format } from "date-fns"

interface SimulationLog {
  id: number
  startTime: string
  duration: number
  vehicleCount: number
  inflowRate: number
  averageSpeed: number
  autoGeneratedRatio: number
  hash: string
  createdAt: string
}

export default function LogsPopup({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const [logs, setLogs] = useState<SimulationLog[]>([])
  const [filteredLogs, setFilteredLogs] = useState<SimulationLog[]>([])
  const [searchTerm, setSearchTerm] = useState("")
  const [sortField, setSortField] = useState<keyof SimulationLog>("startTime")
  const [sortDirection, setSortDirection] = useState<"asc" | "desc">("desc")
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    if (open) {
      fetchLogs()
    }
  }, [open])

  useEffect(() => {
    // Filter logs based on search term
    if (searchTerm.trim() === "") {
      setFilteredLogs(logs)
    } else {
      const term = searchTerm.toLowerCase()
      const filtered = logs.filter(
        (log) =>
          log.startTime.toLowerCase().includes(term) ||
          log.vehicleCount.toString().includes(term) ||
          log.inflowRate.toString().includes(term) ||
          log.averageSpeed.toString().includes(term),
      )
      setFilteredLogs(filtered)
    }
  }, [searchTerm, logs])

  const fetchLogs = async () => {
    setIsLoading(true)
    try {
      const response = await fetch("/api/logs")
      if (response.ok) {
        const data = await response.json()
        setLogs(data.logs)
        setFilteredLogs(data.logs)
      } else {
        console.error("Failed to fetch logs")
      }
    } catch (error) {
      console.error("Error fetching logs:", error)
    } finally {
      setIsLoading(false)
    }
  }

  const handleSort = (field: keyof SimulationLog) => {
    const newDirection = field === sortField && sortDirection === "asc" ? "desc" : "asc"
    setSortField(field)
    setSortDirection(newDirection)

    const sorted = [...filteredLogs].sort((a, b) => {
      if (field === "startTime" || field === "createdAt") {
        const dateA = new Date(a[field])
        const dateB = new Date(b[field])
        return newDirection === "asc" ? dateA.getTime() - dateB.getTime() : dateB.getTime() - dateA.getTime()
      }

      if (typeof a[field] === "number" && typeof b[field] === "number") {
        return newDirection === "asc"
          ? (a[field] as number) - (b[field] as number)
          : (b[field] as number) - (a[field] as number)
      }

      // Default string comparison
      const strA = String(a[field]).toLowerCase()
      const strB = String(b[field]).toLowerCase()
      return newDirection === "asc" ? strA.localeCompare(strB) : strB.localeCompare(strA)
    })

    setFilteredLogs(sorted)
  }

  const exportToCSV = () => {
    if (filteredLogs.length === 0) return

    // Create CSV content
    const headers = [
      "ID",
      "Start Time",
      "Duration (min)",
      "Vehicle Count",
      "Inflow Rate",
      "Average Speed",
      "Auto-Generated Ratio",
      "Created At",
    ]

    const csvContent = [
      headers.join(","),
      ...filteredLogs.map((log) =>
        [
          log.id,
          log.startTime,
          (log.duration / 60).toFixed(2),
          log.vehicleCount,
          log.inflowRate,
          log.averageSpeed.toFixed(2),
          (log.autoGeneratedRatio * 100).toFixed(2) + "%",
          log.createdAt,
        ].join(","),
      ),
    ].join("\n")

    // Create download link
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" })
    const url = URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.setAttribute("href", url)
    link.setAttribute("download", `simulation_logs_${format(new Date(), "yyyy-MM-dd")}.csv`)
    link.style.visibility = "hidden"
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-hidden flex flex-col bg-gray-800 border-gray-700 text-white">
        <DialogHeader>
          <DialogTitle className="text-2xl font-bold">Simulation Logs</DialogTitle>
          <DialogDescription className="text-gray-400">View and analyze past simulation runs</DialogDescription>
        </DialogHeader>

        <div className="flex items-center justify-between mb-4">
          <div className="relative w-64">
            <Search className="absolute left-2 top-2.5 h-4 w-4 text-gray-400" />
            <Input
              placeholder="Search logs..."
              className="pl-8 bg-gray-700 border-gray-600"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              className="bg-gray-700 hover:bg-gray-600 border-gray-600"
              onClick={fetchLogs}
            >
              <RotateCw className="h-4 w-4 mr-2" />
              Refresh
            </Button>
            <Button
              variant="outline"
              size="sm"
              className="bg-gray-700 hover:bg-gray-600 border-gray-600"
              onClick={exportToCSV}
              disabled={filteredLogs.length === 0}
            >
              <Download className="h-4 w-4 mr-2" />
              Export CSV
            </Button>
          </div>
        </div>

        <div className="flex-1 overflow-auto">
          <Table>
            <TableHeader className="bg-gray-700">
              <TableRow>
                <TableHead className="text-gray-300 w-[50px]">#</TableHead>
                <TableHead className="text-gray-300">
                  <button className="flex items-center text-left" onClick={() => handleSort("startTime")}>
                    <Calendar className="h-4 w-4 mr-1" />
                    Start Time
                    {sortField === "startTime" && (
                      <ArrowUpDown className={`h-4 w-4 ml-1 ${sortDirection === "asc" ? "rotate-180" : ""}`} />
                    )}
                  </button>
                </TableHead>
                <TableHead className="text-gray-300">
                  <button className="flex items-center text-left" onClick={() => handleSort("duration")}>
                    <Clock className="h-4 w-4 mr-1" />
                    Duration
                    {sortField === "duration" && (
                      <ArrowUpDown className={`h-4 w-4 ml-1 ${sortDirection === "asc" ? "rotate-180" : ""}`} />
                    )}
                  </button>
                </TableHead>
                <TableHead className="text-gray-300">
                  <button className="flex items-center text-left" onClick={() => handleSort("vehicleCount")}>
                    <Car className="h-4 w-4 mr-1" />
                    Vehicles
                    {sortField === "vehicleCount" && (
                      <ArrowUpDown className={`h-4 w-4 ml-1 ${sortDirection === "asc" ? "rotate-180" : ""}`} />
                    )}
                  </button>
                </TableHead>
                <TableHead className="text-gray-300">
                  <button className="flex items-center text-left" onClick={() => handleSort("inflowRate")}>
                    Inflow Rate
                    {sortField === "inflowRate" && (
                      <ArrowUpDown className={`h-4 w-4 ml-1 ${sortDirection === "asc" ? "rotate-180" : ""}`} />
                    )}
                  </button>
                </TableHead>
                <TableHead className="text-gray-300">
                  <button className="flex items-center text-left" onClick={() => handleSort("averageSpeed")}>
                    <Gauge className="h-4 w-4 mr-1" />
                    Avg Speed
                    {sortField === "averageSpeed" && (
                      <ArrowUpDown className={`h-4 w-4 ml-1 ${sortDirection === "asc" ? "rotate-180" : ""}`} />
                    )}
                  </button>
                </TableHead>
                <TableHead className="text-gray-300">
                  <button className="flex items-center text-left" onClick={() => handleSort("autoGeneratedRatio")}>
                    Auto/Manual
                    {sortField === "autoGeneratedRatio" && (
                      <ArrowUpDown className={`h-4 w-4 ml-1 ${sortDirection === "asc" ? "rotate-180" : ""}`} />
                    )}
                  </button>
                </TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {isLoading ? (
                <TableRow>
                  <TableCell colSpan={7} className="text-center py-8">
                    <div className="flex flex-col items-center justify-center">
                      <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-emerald-500 mb-2"></div>
                      <span className="text-gray-400">Loading logs...</span>
                    </div>
                  </TableCell>
                </TableRow>
              ) : filteredLogs.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={7} className="text-center py-8 text-gray-400">
                    No simulation logs found
                  </TableCell>
                </TableRow>
              ) : (
                filteredLogs.map((log) => (
                  <TableRow key={log.id} className="border-gray-700 hover:bg-gray-700">
                    <TableCell className="font-medium">{log.id}</TableCell>
                    <TableCell>{new Date(log.startTime).toLocaleString()}</TableCell>
                    <TableCell>
                      {Math.floor(log.duration / 60)}h {Math.round(log.duration % 60)}m
                    </TableCell>
                    <TableCell>{log.vehicleCount}</TableCell>
                    <TableCell>{log.inflowRate}/min</TableCell>
                    <TableCell>{log.averageSpeed.toFixed(2)} km/h</TableCell>
                    <TableCell>
                      <div className="flex items-center">
                        <div className="w-full bg-gray-600 rounded-full h-1.5 mr-2">
                          <div
                            className="h-1.5 rounded-full bg-emerald-500"
                            style={{ width: `${log.autoGeneratedRatio * 100}%` }}
                          />
                        </div>
                        <span>{(log.autoGeneratedRatio * 100).toFixed(0)}%</span>
                      </div>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </div>
      </DialogContent>
    </Dialog>
  )
}
