import sqlite3 from "sqlite3"
import { open, type Database } from "sqlite"
import { createHash } from "crypto"
import path from "path"

let db: Database | null = null

export async function getDb() {
  if (!db) {
    // Ensure the database is initialized only once
    db = await open({
      filename: path.join(process.cwd(), "simulation_logs.db"),
      driver: sqlite3.Database,
    })

    // Create tables if they don't exist
    await db.exec(`
      CREATE TABLE IF NOT EXISTS simulation_logs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        start_time TEXT NOT NULL,
        duration REAL NOT NULL,
        vehicle_count INTEGER NOT NULL,
        inflow_rate REAL NOT NULL,
        average_speed REAL NOT NULL,
        auto_generated_ratio REAL NOT NULL,
        hash TEXT NOT NULL,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
      )
    `)
  }

  return db
}

export interface SimulationLogData {
  startTime: string
  duration: number
  vehicleCount: number
  inflowRate: number
  averageSpeed: number
  autoGeneratedRatio: number
}

export async function createSimulationLog(data: SimulationLogData) {
  const db = await getDb()

  // Create a hash of the data for integrity verification
  const hash = createHash("sha256")
    .update(
      `${data.startTime}|${data.duration}|${data.vehicleCount}|${data.inflowRate}|${data.averageSpeed}|${data.autoGeneratedRatio}`,
    )
    .digest("hex")

  const result = await db.run(
    `INSERT INTO simulation_logs 
     (start_time, duration, vehicle_count, inflow_rate, average_speed, auto_generated_ratio, hash)
     VALUES (?, ?, ?, ?, ?, ?, ?)`,
    [
      data.startTime,
      data.duration,
      data.vehicleCount,
      data.inflowRate,
      data.averageSpeed,
      data.autoGeneratedRatio,
      hash,
    ],
  )

  return result.lastID
}

export async function getSimulationLogs() {
  const db = await getDb()

  const logs = await db.all(`
    SELECT 
      id,
      start_time as startTime,
      duration,
      vehicle_count as vehicleCount,
      inflow_rate as inflowRate,
      average_speed as averageSpeed,
      auto_generated_ratio as autoGeneratedRatio,
      hash,
      created_at as createdAt
    FROM simulation_logs
    ORDER BY created_at DESC
  `)

  return logs
}

export async function verifyLogIntegrity(id: number) {
  const db = await getDb()

  const log = await db.get(
    `
    SELECT 
      start_time as startTime,
      duration,
      vehicle_count as vehicleCount,
      inflow_rate as inflowRate,
      average_speed as averageSpeed,
      auto_generated_ratio as autoGeneratedRatio,
      hash
    FROM simulation_logs
    WHERE id = ?
  `,
    [id],
  )

  if (!log) return false

  const calculatedHash = createHash("sha256")
    .update(
      `${log.startTime}|${log.duration}|${log.vehicleCount}|${log.inflowRate}|${log.averageSpeed}|${log.autoGeneratedRatio}`,
    )
    .digest("hex")

  return calculatedHash === log.hash
}
